name: Periodic Commit

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Training pipeline
      run: |
      python scraper.py
      python cleaning.py
      python preprocessing.py
      python trainer.py

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Automated commit :) ' "
        git push
